apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: portfolio
build:
  artifacts:
    - image: portfolio
      sync:
        manual:
          - src: "./src/**/*.tsx"
            dest: .
          - src: "./src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes-prod.yml